INSERT INTO tb_user (name, email, password) VALUES ('Bob Green', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana White', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre (name) VALUES ('Ação');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Ficção Científica');

INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Veloses e Furiosos 8', null, 2017, 'https://razaodeaspecto.com/wp-content/uploads/2017/04/1003-velozes-e-furiosos-8-saiu-o-novo-trailer-completo-do-filme-tb.jpg', 'Dom (Vin Diesel) e Letty (Michelle Rodriguez) estão curtindo a lua de mel em Havana, mas a súbita aparição de Cipher (Charlize Theron) atrapalha os planos do casal. Ela logo arma um plano para chantagear Dom, de forma que ele traia seus amigos e passe a ajudá-la a obter ogivas nucleares. Tal situação faz com Letty reúna os velhos amigos, que agora precisam enfrentar Cipher e, consequentemente, Dom.', 1);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Gladiador', null, 2000, 'https://www.culturaprojetada.com.br/wp-content/uploads/2020/05/gladiador-feed.jpg', 'Nos dias finais do reinado de Marcus Aurelius (Richard Harris), o imperador desperta a ira de seu filho Commodus (Joaquin Phoenix) ao tornar pública sua predileção em deixar o trono para Maximus (Russell Crowe), o comandante do exército romano. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus, que consegue fugir antes de ser pego e passa a se esconder sob a identidade de um escravo e gladiador do Império Romano.', 1);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('007 - Cassino Royale', null, 2006, 'https://universoestendido.com.br/wp-content/uploads/2018/05/007-cassino-royale-2006-1.jpg', 'A 1ª missão de James Bond (Daniel Craig) como agente 007 o leva a Madagascar. Sua tarefa é espionar o terrorista Mollaka (Sebastien Foucan), mas nem tudo sai como o planejado. Bond decide espionar por conta própria o restante da célula terrorista, o que o leva às Bahamas. Lá ele conhece Alex Dimitrios (Simon Abkarian) e sua namorada Solange (Caterina Murino). Alex está envolvido com Le Chiffre (Mads Mikkelsen), o banqueiro de organizações terroristas espalhadas pelo planeta, que pretende conseguir dinheiro em um jogo de pôquer milionário em Montenegro, no Cassino Royale. O MI6 envia Bond para jogar contra Le Chiffre, sabendo que caso Le Chiffre perca a partida isto desmontará sua organização. Mas para esta tarefa o agente 007 terá a companhia da sedutora Vesper Lynd (Eva Green), enviada por M (Judi Dench) para acompanhá-lo na missão.', 1);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Debi & Lóide 2', null, 2014, 'http://br.web.img3.acsta.net/videothumbnails/14/06/11/14/18/498887.jpg', 'Mais nova aventura dos inseparáveis Lloyd Christmas (Jim Carrey) e Harry Dunne (Jeff Daniels). Desta vez, Harry descobre que teve uma filha ilegítima, que hoje precisa dele para um transplante de rim. Ele leva o amigo Lloyd para conhecer a garota, e os dois percebem que não têm a responsabilidade necessária para serem pais.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Gente Grande', null, 2010, 'http://br.web.img2.acsta.net/videothumbnails/189/518/18951851_2013082118111215.jpg', 'Em Gente Grande, Lenny (Adam Sandler), Kurt (Chris Rock), Eric (Kevin James), Marcus (David Spade) e Rob (Rob Schneider) se conhecem desde pequenos. Passados trinta anos, os cinco amigos se reencontram para curtir um fim de semana juntos com as respectivas famílias, mas o feriado de 4 de Julho em uma casa no lago promete muito mais diversão do que apenas lembranças dos bons momentos. Casados e com várias crianças, os homens de família terão de confrontar o fato de não serem mais tão jovens.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Babá fora de Controle', 'Missão Brasil', 2016, 'https://i.ytimg.com/vi/GnppMD_x-p4/maxresdefault.jpg', 'Namorada de Frank (Philippe Lacheau), Sonya (Alice David) deseja apresentá-lo ao seu pai, Jean-Pierre, diretor de um hotel ecológico no Brasil. Os dois e um grupo de amigos viajam ao local para tirar férias. Certa manhã, Frank e os amigos decidem fazer uma excursão na floresta amazônica e Jean-Pierre confia a eles sua mãe rabugenta, Yolande (Valériane de Villeneuve). No dia seguinte, todos estão desaparecidos. Sonya e Jean-Pierre encontram uma câmera, em que está registrada tudo o ue aconteceu com eles.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Os Farofeiros', null, 2018, 'https://i2.wp.com/ocapacitor.com/wp-content/uploads/2018/02/banner-os-farofeiros.jpg', 'Quatro colegas de trabalho se programam para curtir o feriado prolongado em uma casa de praia e, chegando lá, descobrem que se meteram em uma tremenda roubada. Para começar o destino não é Búzios, mas Maringuaba; a residência alugada é encontrada caindo aos pedaços, bem diferente do prometido; a praia está sempre cheia; e as confusões são inúmeras.', 2);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Avatar', null, 2010, 'https://wallpapersfull.com/wallpapers/2019/poster-do-filme-avatar-4627.jpg', 'Jake Sully (Sam Worthington) ficou paraplégico após um combate na Terra. Ele é selecionado para participar do programa Avatar em substituição ao seu irmão gêmeo, falecido. Jake viaja a Pandora, uma lua extraterrestre, onde encontra diversas e estranhas formas de vida. O local é também o lar dos NaVi, seres humanóides que, apesar de primitivos, possuem maior capacidade física que os humanos. Os NaVi têm três metros de altura, pele azulada e vivem em paz com a natureza de Pandora. Os humanos desejam explorar a lua, de forma a encontrar metais valiosos, o que faz com que os NaVi aperfeiçoem suas habilidades guerreiras. Como são incapazes de respirar o ar de Pandora, os humanos criam seres híbridos chamados de Avatar. Eles são controlados por seres humanos, através de uma tecnologia que permite que seus pensamentos sejam aplicados no corpo do Avatar. Desta forma Jake pode novamente voltar à ativa, com seu Avatar percorrendo as florestas de Pandora e liderando soldados. Até conhecer Neytiri (Zoe Saldana), uma feroz NaVi que conhece acidentalmente e que serve de tutora para sua ambientação na civilização alienígena.', 3);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('Liga da Justiça', 'Snyder Cut', 2021, 'https://super.abril.com.br/wp-content/uploads/2020/05/si_justice_league_hbo.jpg', 'Depois de restaurar sua fé na humanidade e inspirado pelo ato altruísta do Superman, Bruce Wayne convoca Diana Prince para combater um inimigo ainda maior, recém-despertado. Juntos, Batman e Mulher-Maravilha buscam e recrutam um time de meta-humanos, mas mesmo com a formação da liga de heróis sem precedentes -- Batman, Mulher-Maravilha, Aquaman, Ciborgue, e Flash -- poderá ser tarde demais para salvar o planeta de um catastrófico ataque.', 3);
INSERT INTO tb_movie (title, subtitle, year, img_Url, synopsis, genre_id) VALUES ('De Volta para o Futuro', null, 1985, 'https://deveserisso.com.br/blog/wp-content/uploads/2019/09/de-volta-para-o-futuro.jpg', 'Um jovem (Michael J. Fox) aciona acidentalmente uma máquina do tempo construída por um cientista (Christopher Lloyd) em um Delorean, retornando aos anos 50. Lá conhece sua mãe (Lea Thompson), antes ainda do casamento com seu pai, que fica apaixonada por ele. Tal paixão põe em risco sua própria existência, pois alteraria todo o futuro, forçando-o a servir de cupido entre seus pais.', 3);

INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Muito bom!', 1, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Excelente', 2, 1);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Dei muita risada', 1, 4);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Para rir muito', 1, 6);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('O melhor filme de comédia brasileiro', 2, 7);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Fenomenal', 2, 7);
INSERT INTO tb_review (text, user_id, movie_id) VALUES ('Inesquecível', 1, 8);
